# Generated by Django 6.0.5 on 2026-06-06 09:40

from django.db import migrations, models


def set_existing_notes_to_published(apps, schema_editor):
    Note = apps.get_model('app', 'Note')
    Note.objects.filter(ispublished=False).update(ispublished=True)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_note_ai_organized_note_ai_summary_note_ai_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='ispublished',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_existing_notes_to_published, migrations.RunPython.noop),
    ]
