# Generated by Django 6.0.5 on 2026-06-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ai_flashcards',
            field=models.TextField(blank=True, null=True),
        ),
    ]
